# Rename this file to languages.toml to enable multilingual support
[pt]
    languageName      = "PortuguÃªs Brasil"
    languagedirection = "ltr"
    title             = "Universitas"
    weight            = 1
