[[social]]
    identifier = "Whatsapp"
    name       = "Whatsapp"
    url        = "https://wa.me/551992400792"
    newtab = true
    [social.params]
        icon = "whatsapp"
[[social]]
    identifier = "Instagram"
    name       = "Instagram"
    url        = "https://instagram.com/universitas.solutions"
    newtab = true
    [social.params]
        icon = "brand-instagram"
[[social]]
    identifier = "Email"
    name       = "Email"
    url        = "mailto:geraldohomero+universitas@pm.me"
    newtab = true
    [social.params]
        icon = "email"